---

- name: Make sure rsyslog is installed
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: '{{ rsyslog_packages }}'
  when: rsyslog_packages is defined and rsyslog_packages
  notify: [ 'Restart rsyslogd' ]

- include: pools.yml
  when: rsyslog_manage_pools is defined and rsyslog_manage_pools == True
