---
- name: Divert the custom rsyslog configuration
  environment:
    LC_ALL: 'C'
  command: dpkg-divert --local --divert /etc/rsyslog.d/{{ item.divert_to | d(item.filename + ".dpkg-divert") }} --rename /etc/rsyslog.d/{{ item.filename }}
  args:
    creates: '/etc/rsyslog.d/{{ item.divert_to | d(item.filename + ".dpkg-divert") }}'
  register: rsyslog__register_divert_rules
  with_flattened:
    - '{{ rsyslog_pools | d([]) }}'
    - '{{ rsyslog__default_rules }}'
    - '{{ rsyslog__rules }}'
    - '{{ rsyslog__group_rules }}'
    - '{{ rsyslog__host_rules }}'
    - '{{ rsyslog__dependent_rules }}'
  when: (rsyslog__enabled|bool and item.filename|d() and
         (item.state is undefined or item.state != 'absent') and
         (item.divert|d() and item.divert|bool))
  changed_when: rsyslog__register_divert_rules.stdout.startswith("Adding 'local diversion of ")
  notify: [ 'Restart rsyslogd' ]

- name: Generate rsyslog configuration rules
  template:
    src: 'etc/rsyslog.d/rules.conf.j2'
    dest: '/etc/rsyslog.d/{{ item.filename | d((item.weight if item.weight|d() else rsyslog__weight_map[item.type|d("rules")]) + "-" + (item.name|d("rules")) + "." + (item.suffix |d ("conf"))) }}'
    owner: '{{ item.owner | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode:  '{{ item.mode  | d("0644") }}'
  with_flattened:
    - '{{ rsyslog_pools | d([]) }}'
    - '{{ rsyslog__default_rules }}'
    - '{{ rsyslog__rules }}'
    - '{{ rsyslog__group_rules }}'
    - '{{ rsyslog__host_rules }}'
    - '{{ rsyslog__dependent_rules }}'
  when: (rsyslog__enabled|bool and (item.filename|d() or item.name|d()) and
         (item.state is undefined or item.state != 'absent') and
         (item.options|d() or item.sections|d()))
  notify: [ 'Restart rsyslogd' ]

- name: Remove custom config files when requested
  file:
    path: '/etc/rsyslog.d/{{ item.filename | d((item.weight if item.weight|d() else rsyslog__weight_map[item.type|d("rules")]) + "-" + (item.name|d("rules")) + "." + (item.suffix | d("conf"))) }}'
    state: 'absent'
  with_flattened:
    - '{{ rsyslog_pools | d([]) }}'
    - '{{ rsyslog__default_rules }}'
    - '{{ rsyslog__rules }}'
    - '{{ rsyslog__group_rules }}'
    - '{{ rsyslog__host_rules }}'
    - '{{ rsyslog__dependent_rules }}'
  when: (not rsyslog__enabled|bool or
         ((item.filename|d() or item.name|d()) and
          (item.state|d() and item.state == 'absent')) and
         (item.options|d() or item.sections|d())) and
        (item.divert is undefined or not item.divert|bool)
  notify: [ 'Restart rsyslogd' ]

- name: Revert original rsyslog config rules
  shell: rm -f /etc/rsyslog.d/{{ item.filename }} ; dpkg-divert --quiet --local --rename --remove /etc/rsyslog.d/{{ item.filename }}
  args:
    removes: '/etc/rsyslog.d/{{ item.divert_to | d(item.filename + ".dpkg-divert") }}'
    warn: False
  with_flattened:
    - '{{ rsyslog_pools | d([]) }}'
    - '{{ rsyslog__default_rules }}'
    - '{{ rsyslog__rules }}'
    - '{{ rsyslog__group_rules }}'
    - '{{ rsyslog__host_rules }}'
    - '{{ rsyslog__dependent_rules }}'
  when: ((not rsyslog__enabled|bool or
          (item.filename|d() and (item.state|d() and item.state == 'absent'))) and
         (item.divert|d() and item.divert|bool))
  notify: [ 'Restart rsyslogd' ]